//! Custom resource definitions: `Homeserver`, `AppService`, `Bridge`, `PushGateway` and
//! `IdentityService`, all in the `hs.matrix.org/v1alpha1` API group. Each kind's module has the
//! full rationale; [`all_crds`] is the entry point [`crate::bin::gen_crds`] (and the schema
//! round-trip tests) use to enumerate every one of them in one place.

pub mod appservice;
pub mod bridge;
pub mod common;
pub mod homeserver;
pub mod identityservice;
pub mod pushgateway;

pub use appservice::{AppService, AppServiceSpec};
pub use bridge::{Bridge, BridgeSpec, BridgeStorage};
pub use common::{ImageSpec, OperatorStatus, Phase, SecretKeyRef};
pub use homeserver::{
    AdminApiSpec, AntiAffinity, ClusterSpec, DrainReason, DrainSpec, DrainStatus,
    DrainTimeoutPolicy, EmbeddedStorageSpec, Homeserver, HomeserverSpec, HomeserverStatus,
    MediaBackend, MediaSpec, PendingUndrain, PostgresStorageSpec, S3MediaSpec, SlatedbStorageSpec,
    StorageBackend, StorageSpec, UndrainWhen,
};
pub use identityservice::{IdentityService, IdentityServiceSpec};
pub use pushgateway::{PushGateway, PushGatewaySpec};

use k8s_openapi::apiextensions_apiserver::pkg::apis::apiextensions::v1::CustomResourceDefinition;
use kube::CustomResourceExt as _;

/// Every CRD this operator defines, with a short label for use in filenames/log lines. Kept as
/// one function so a new kind is wired into codegen (`gen-crds`) and the schema round-trip test
/// below by adding one line here, not by updating several call sites that could drift out of
/// sync.
#[must_use]
pub fn all_crds() -> Vec<(&'static str, CustomResourceDefinition)> {
    vec![
        ("homeserver", Homeserver::crd()),
        ("appservice", AppService::crd()),
        ("bridge", Bridge::crd()),
        ("pushgateway", PushGateway::crd()),
        ("identityservice", IdentityService::crd()),
    ]
    .into_iter()
    .map(|(label, crd)| (label, with_kubernetes_formats(crd)))
    .collect()
}

/// The CRD with schemars' unsigned integer formats (`uint32`, `uint64`, ...) replaced by
/// `int64`, the format Kubernetes knows; the `minimum: 0` schemars writes beside them keeps
/// them unsigned. The API server accepts the unknown ones but warns on every apply
/// ("unrecognized format \"uint64\""), seen on the first apply to a real cluster (2026-10-01).
fn with_kubernetes_formats(crd: CustomResourceDefinition) -> CustomResourceDefinition {
    fn rewrite(value: &mut serde_json::Value) {
        match value {
            serde_json::Value::Object(map) => {
                if let Some(serde_json::Value::String(format)) = map.get_mut("format")
                    && format.starts_with("uint")
                {
                    "int64".clone_into(format);
                }
                map.values_mut().for_each(rewrite);
            }
            serde_json::Value::Array(items) => items.iter_mut().for_each(rewrite),
            _ => {}
        }
    }
    // A CRD always round-trips through JSON; on the impossible failure keep it as generated.
    let Ok(mut value) = serde_json::to_value(&crd) else {
        return crd;
    };
    rewrite(&mut value);
    serde_json::from_value(value).unwrap_or(crd)
}

/// Where the Helm chart keeps its copy of the `Bridge` CRD, relative to the workspace root.
/// `gen-crds` writes it beside `deploy/crds/bridge.yaml`.
pub const CHART_BRIDGE_CRD: &str = "deploy/helm/hs/crds/bridge.yaml";

/// The exact text `gen-crds` writes for one CRD: a do-not-edit header and the YAML.
///
/// # Errors
/// When the CRD cannot be rendered as YAML (it always can).
pub fn render(label: &str, crd: &CustomResourceDefinition) -> Result<String, serde_yaml_ng::Error> {
    let yaml = serde_yaml_ng::to_string(crd)?;
    Ok(format!(
        "# Generated by `cargo run -p hs-operator --bin gen-crds`. Do not hand-edit; change the \
         CRD's Rust struct in crates/hs-operator/src/crds/{label}.rs and regenerate.\n{yaml}"
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_files_are_up_to_date() {
        // The committed YAML (and the chart's copy of the Bridge CRD) is what clusters get; it
        // must be exactly what the Rust structs generate. Fix with `cargo run -p hs-operator
        // --bin gen-crds`.
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        for (label, crd) in all_crds() {
            let expected = render(label, &crd).unwrap();
            let path = root.join(format!("deploy/crds/{label}.yaml"));
            let actual = std::fs::read_to_string(&path).unwrap();
            assert!(
                actual == expected,
                "{} is stale: run `cargo run -p hs-operator --bin gen-crds`",
                path.display()
            );
            if label == "bridge" {
                let chart = std::fs::read_to_string(root.join(CHART_BRIDGE_CRD)).unwrap();
                assert!(
                    chart == expected,
                    "{CHART_BRIDGE_CRD} differs from deploy/crds/bridge.yaml: run gen-crds"
                );
            }
        }
    }

    #[test]
    fn every_crd_has_the_expected_group_and_a_stored_version() {
        for (label, crd) in all_crds() {
            assert_eq!(crd.spec.group, "hs.matrix.org", "{label}");
            assert!(
                crd.spec.versions.iter().any(|v| v.served && v.storage),
                "{label} has no served+stored version"
            );
        }
    }

    #[test]
    fn every_crd_schema_round_trips_through_yaml() {
        // Proves gen-crds' actual output path (CRD -> YAML -> re-parsed) is well-formed for
        // every kind, not just that the Rust structs serialize.
        for (label, crd) in all_crds() {
            let yaml = serde_yaml_ng::to_string(&crd).unwrap_or_else(|e| {
                panic!("{label}: failed to render CRD as YAML: {e}");
            });
            let reparsed: serde_yaml_ng::Value = serde_yaml_ng::from_str(&yaml)
                .unwrap_or_else(|e| panic!("{label}: rendered YAML did not reparse: {e}"));
            assert_eq!(
                reparsed["kind"].as_str(),
                Some("CustomResourceDefinition"),
                "{label}"
            );
        }
    }

    #[test]
    fn every_integer_format_is_one_kubernetes_knows() {
        // The API server warns on every apply of a schema with `format: uint32`; the unsigned
        // fields keep their `minimum: 0` instead.
        for (label, crd) in all_crds() {
            let yaml = render(label, &crd).unwrap();
            assert!(!yaml.contains("format: uint"), "{label}");
            if label == "homeserver" {
                assert!(yaml.contains("format: int64"), "{label}");
            }
        }
    }

    #[test]
    fn kind_names_are_the_five_specified_in_the_brief() {
        let kinds: Vec<String> = all_crds()
            .into_iter()
            .map(|(_, crd)| crd.spec.names.kind)
            .collect();
        for expected in [
            "Homeserver",
            "AppService",
            "Bridge",
            "PushGateway",
            "IdentityService",
        ] {
            assert!(
                kinds.iter().any(|k| k == expected),
                "missing kind {expected}"
            );
        }
    }
}
