//! `hs generate-config`: writes a minimal, valid native `hs-config` YAML file for a given
//! server name, the moral equivalent of Synapse's own `generate_config` first-run helper (and of
//! the Docker entrypoint's `SYNAPSE_SERVER_NAME`-driven config generation described in
//! `docs/compat/cli-shims.md`'s environment-variable table).

use hs_config::Config;

/// Builds a minimal valid [`Config`] for `server_name`, with everything else left at its
/// documented default (see each section's rustdoc in `hs-config`).
#[must_use]
pub fn minimal_config(server_name: &str) -> Config {
    let mut config = Config::default();
    config.server.server_name = server_name.to_owned();
    config
}

/// Renders `config` as YAML, with a short explanatory header comment (matching Synapse's own
/// generated-config header, which points an operator at the file's provenance).
///
/// # Errors
/// Returns a `serde_yaml_ng` error if `config` somehow fails to serialize (it always succeeds
/// for a `Config` value that passed validation; the `Result` exists because serialization is
/// fallible in general).
pub fn render_yaml(config: &Config, server_name: &str) -> Result<String, serde_yaml_ng::Error> {
    let body = serde_yaml_ng::to_string(config)?;
    Ok(format!(
        "# Generated by `hs generate-config` for server_name {server_name:?}.\n\
         # Review every value below before using this in production — in particular,\n\
         # `server.signing_key_path` (run `hs generate-signing-key` to populate it) and\n\
         # `storage` (defaults to the embedded single-node backend).\n\
         {body}"
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn minimal_config_is_valid() {
        let config = minimal_config("example.org");
        config.validate().unwrap();
    }

    #[test]
    fn rendered_yaml_round_trips_through_from_yaml() {
        let config = minimal_config("example.org");
        let yaml = render_yaml(&config, "example.org").unwrap();
        let parsed = Config::from_yaml(&yaml).unwrap();
        assert_eq!(parsed.server.server_name, "example.org");
    }
}
