//! `hs generate-signing-key`: writes a new Ed25519 signing key in Synapse's `signing.key` text
//! format (`docs/compat/cli-shims.md`), so a key generated by either tool is a drop-in read for
//! the other.
//!
//! Ed25519 key generation is deliberately done directly against `ed25519-dalek` here rather than
//! through `hs-model::signing::SigningKeyPair` (which this crate would otherwise prefer to
//! reuse): that type does not expose its private key bytes (by design — nothing else in the
//! workspace needs to serialize a private signing key to a file), so there is nothing to write to
//! disk in Synapse's format without either adding an accessor to `hs-model` (a crate this track
//! does not own) or generating the key independently, as this module does.

use base64::Engine as _;
use base64::engine::general_purpose::STANDARD_NO_PAD;
use ed25519_dalek::SigningKey;
use rand::Rng as _;
use rand::distr::Alphanumeric;

/// The algorithm name written into the signing key file. Matches `hs_model::signing::ALGORITHM`
/// and Synapse's own key file format (`ed25519 <key_id> <base64 seed>`).
const ALGORITHM: &str = "ed25519";

/// Generates a random key ID version in the same shape Synapse's own `generate_signing_key`
/// script uses (a short random alphanumeric string prefixed `a_`), so key IDs from either tool
/// look the same to an operator scanning a directory of them.
fn random_key_id_version() -> String {
    let suffix: String = rand::rng()
        .sample_iter(&Alphanumeric)
        .take(6)
        .map(char::from)
        .collect();
    format!("a_{suffix}")
}

/// Generates a fresh Ed25519 signing key and formats it as one Synapse-shaped signing-key line:
/// `<algorithm> <key_id> <base64-private-key>\n`.
#[must_use]
pub fn generate_signing_key_line() -> String {
    let key = SigningKey::generate(&mut rand_core::OsRng);
    let key_id = random_key_id_version();
    let encoded = STANDARD_NO_PAD.encode(key.to_bytes());
    format!("{ALGORITHM} {key_id} {encoded}\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn produces_three_whitespace_separated_fields() {
        let line = generate_signing_key_line();
        let fields: Vec<&str> = line.trim_end().split(' ').collect();
        assert_eq!(fields.len(), 3);
        assert_eq!(fields[0], "ed25519");
        assert!(fields[1].starts_with("a_"));
    }

    #[test]
    fn the_base64_field_decodes_to_a_32_byte_seed() {
        let line = generate_signing_key_line();
        let fields: Vec<&str> = line.trim_end().split(' ').collect();
        let decoded = STANDARD_NO_PAD.decode(fields[2]).unwrap();
        assert_eq!(decoded.len(), 32);
    }

    #[test]
    fn two_generated_keys_are_different() {
        let a = generate_signing_key_line();
        let b = generate_signing_key_line();
        assert_ne!(a, b);
    }
}
