//! `hs-config`: the native homeserver configuration schema.
//!
//! Owned by track 13 (`docs/workstreams/13-config-compat-and-migration.md`).
//! See `PLAN.md` section 5.5 for this crate's place in the workspace.
//!
//! # Loading a configuration
//!
//! ```no_run
//! use hs_config::Config;
//!
//! let config = Config::load(std::path::Path::new("homeserver.yaml"))?;
//! # Ok::<(), hs_config::ConfigError>(())
//! ```
//!
//! [`Config::load`] reads the YAML file, applies every `HS__section__key`
//! environment variable found in the process environment (see the [`env`]
//! module), resolves `*_file` secret references (see the [`secret`]
//! module), and validates the result, collecting every problem before
//! returning ([`ConfigError::Validation`]) rather than stopping at the
//! first one.
//!
//! # The reload boundary
//!
//! Not every section may change on a running server without a restart; see
//! the [`reload`] module for the policy and [`reload::sections_requiring_restart`]
//! to check a candidate new configuration against a running one.

pub mod appservice;
pub mod auth;
pub mod cluster;
pub mod duration;
pub mod env;
pub mod error;
pub mod federation;
pub mod listeners;
pub mod media;
pub mod ratelimit;
pub mod reload;
pub mod secret;
pub mod server;
pub mod size;
pub mod storage;
pub mod telemetry;

use std::path::Path;

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

pub use appservice::AppservicesConfig;
pub use auth::AuthConfig;
pub use cluster::ClusterConfig;
pub use duration::{Duration, DurationParseError};
pub use error::{ConfigError, Validate, ValidationError, ValidationErrors};
pub use federation::FederationConfig;
pub use listeners::ListenersConfig;
pub use media::MediaConfig;
pub use ratelimit::RateLimitConfig;
pub use secret::SecretString;
pub use server::ServerConfig;
pub use size::{ByteSize, ByteSizeParseError};
pub use storage::StorageConfig;
pub use telemetry::TelemetryConfig;

/// The complete native configuration. See each field's module for the
/// options it covers and `docs/config.md` (generated by the
/// `gen_config_docs` binary in this crate) for the rendered reference.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct Config {
    /// Server identity: name, public URL, signing keys.
    #[serde(default)]
    pub server: ServerConfig,
    /// HTTP listeners.
    #[serde(default)]
    pub listeners: ListenersConfig,
    /// Storage backend selection.
    #[serde(default)]
    pub storage: StorageConfig,
    /// Media repository.
    #[serde(default)]
    pub media: MediaConfig,
    /// Federation policy.
    #[serde(default)]
    pub federation: FederationConfig,
    /// Rate limits.
    #[serde(default)]
    pub rate_limits: RateLimitConfig,
    /// Authentication and authorization.
    #[serde(default)]
    pub auth: AuthConfig,
    /// Appservice (bridge) registry bootstrap.
    #[serde(default)]
    pub appservices: AppservicesConfig,
    /// Metrics, tracing, logging and error reporting.
    #[serde(default)]
    pub telemetry: TelemetryConfig,
    /// Cluster topology.
    #[serde(default)]
    pub cluster: ClusterConfig,
}

impl Config {
    /// Parses `yaml`, applies the given environment overrides, resolves
    /// secrets and validates. This is the deterministic core `load` is
    /// built on; tests use it directly to avoid touching the process
    /// environment.
    pub fn from_yaml_with_env<I>(yaml: &str, env_vars: I) -> Result<Config, ConfigError>
    where
        I: IntoIterator<Item = (String, String)>,
    {
        let mut value: serde_yaml_ng::Value = serde_yaml_ng::from_str(yaml)?;
        env::apply_env_overrides(&mut value, env_vars);
        Self::from_value(value)
    }

    /// Parses `yaml` with no environment overrides applied.
    pub fn from_yaml(yaml: &str) -> Result<Config, ConfigError> {
        Self::from_yaml_with_env(yaml, std::iter::empty())
    }

    /// Deserializes an already-parsed YAML value, then resolves secrets and
    /// validates.
    pub fn from_value(value: serde_yaml_ng::Value) -> Result<Config, ConfigError> {
        let mut config: Config = serde_yaml_ng::from_value(value)?;
        config.resolve_secrets()?;
        config.validate()?;
        Ok(config)
    }

    /// Reads `path`, applies every `HS__` variable in the process
    /// environment, resolves secrets and validates.
    pub fn load(path: &Path) -> Result<Config, ConfigError> {
        let raw = std::fs::read_to_string(path).map_err(|source| ConfigError::ReadFile {
            path: path.to_owned(),
            source,
        })?;
        let mut value: serde_yaml_ng::Value = serde_yaml_ng::from_str(&raw)?;
        env::apply_process_env_overrides(&mut value);
        Self::from_value(value)
    }

    /// Resolves every `*_file` secret across every section, mutating in
    /// place. Called automatically by [`Config::from_value`]; exposed for
    /// callers that build a `Config` by other means (e.g. the `hs-compat`
    /// translator).
    pub fn resolve_secrets(&mut self) -> Result<(), ConfigError> {
        self.storage.resolve_secrets("storage")?;
        self.media.resolve_secrets("media")?;
        self.auth.resolve_secrets("auth")?;
        self.telemetry.resolve_secrets("telemetry")?;
        self.cluster.resolve_secrets("cluster")?;
        Ok(())
    }

    /// Validates every section, collecting every problem rather than
    /// stopping at the first.
    pub fn validate(&self) -> Result<(), ConfigError> {
        let mut errors = ValidationErrors::new();
        self.server.validate("server", &mut errors);
        self.listeners.validate("listeners", &mut errors);
        self.storage.validate("storage", &mut errors);
        self.media.validate("media", &mut errors);
        self.federation.validate("federation", &mut errors);
        self.rate_limits.validate("rate_limits", &mut errors);
        self.auth.validate("auth", &mut errors);
        self.appservices.validate("appservices", &mut errors);
        self.telemetry.validate("telemetry", &mut errors);
        self.cluster.validate("cluster", &mut errors);
        errors.into_result()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const MINIMAL: &str = r#"
server:
  server_name: example.org
"#;

    #[test]
    fn minimal_config_parses_and_validates() {
        let cfg = Config::from_yaml(MINIMAL).unwrap();
        assert_eq!(cfg.server.server_name, "example.org");
        assert!(matches!(cfg.storage, StorageConfig::Embedded(_)));
    }

    #[test]
    fn empty_document_fails_validation_on_server_name() {
        let err = Config::from_yaml("{}").unwrap_err();
        match err {
            ConfigError::Validation(errors) => {
                assert!(errors.0.iter().any(|e| e.path == "server.server_name"));
            }
            other => panic!("expected a validation error, got {other:?}"),
        }
    }

    #[test]
    fn unknown_top_level_key_is_rejected() {
        let yaml = "server:\n  server_name: example.org\nnotasection: 1\n";
        let err = Config::from_yaml(yaml).unwrap_err();
        assert!(matches!(err, ConfigError::Parse(_)));
    }

    #[test]
    fn env_override_wins_over_file() {
        let cfg = Config::from_yaml_with_env(
            MINIMAL,
            [(
                "HS__SERVER__SERVER_NAME".to_string(),
                "override.example".to_string(),
            )],
        )
        .unwrap();
        assert_eq!(cfg.server.server_name, "override.example");
    }

    #[test]
    fn env_override_sets_a_field_nested_under_an_absent_section() {
        // `federation` is entirely absent from MINIMAL, and every
        // `FederationConfig` field has its own `serde(default = ...)`, so
        // the single overridden leaf combines with the rest of the
        // section's individual defaults.
        let cfg = Config::from_yaml_with_env(
            MINIMAL,
            [(
                "HS__FEDERATION__CLIENT_TIMEOUT".to_string(),
                "45s".to_string(),
            )],
        )
        .unwrap();
        assert_eq!(cfg.federation.client_timeout, Duration::from_secs(45));
        assert!(
            cfg.federation.verify_certificates,
            "sibling fields still get their own defaults"
        );
    }

    #[test]
    fn env_override_of_one_rate_limit_bucket_field_needs_the_bucket_already_present() {
        // RateLimitBucket's two fields (`per_second`, `burst_count`) are not
        // individually defaulted (see the doc comment on
        // `ratelimit::RateLimitBucket`), because their defaults vary per
        // named bucket and a per-field `serde(default = ...)` cannot see
        // which bucket it is filling in. Overriding just one field of a
        // bucket via `HS__` therefore requires the base config to already
        // spell out that bucket in full.
        let yaml = "server:\n  server_name: example.org\nrate_limits:\n  login:\n    per_second: 0.17\n    burst_count: 3\n";
        let cfg = Config::from_yaml_with_env(
            yaml,
            [(
                "HS__RATE_LIMITS__LOGIN__PER_SECOND".to_string(),
                "0.5".to_string(),
            )],
        )
        .unwrap();
        assert_eq!(cfg.rate_limits.login.per_second, 0.5);
        assert_eq!(cfg.rate_limits.login.burst_count, 3);

        // Without the base bucket present, the same override is a parse
        // error (missing `burst_count`), not a silently-wrong bucket.
        let err = Config::from_yaml_with_env(
            MINIMAL,
            [(
                "HS__RATE_LIMITS__LOGIN__PER_SECOND".to_string(),
                "0.5".to_string(),
            )],
        )
        .unwrap_err();
        assert!(matches!(err, ConfigError::Parse(_)));
    }

    #[test]
    fn env_override_can_select_storage_backend() {
        let cfg = Config::from_yaml_with_env(
            MINIMAL,
            [
                ("HS__STORAGE__BACKEND".to_string(), "postgres".to_string()),
                ("HS__STORAGE__HOST".to_string(), "db.internal".to_string()),
                ("HS__STORAGE__DATABASE".to_string(), "hs".to_string()),
                ("HS__STORAGE__USER".to_string(), "hs".to_string()),
            ],
        )
        .unwrap();
        match cfg.storage {
            StorageConfig::Postgres(p) => assert_eq!(p.host, "db.internal"),
            other => panic!("expected Postgres, got {other:?}"),
        }
    }

    #[test]
    fn secret_file_is_read_at_load_time() {
        let dir = std::env::temp_dir().join(format!("hs-config-lib-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let secret_path = dir.join("reg_secret");
        std::fs::write(&secret_path, "s3cret\n").unwrap();

        let yaml = format!(
            "server:\n  server_name: example.org\nauth:\n  registration_shared_secret_file: {:?}\n",
            secret_path
        );
        let cfg = Config::from_yaml(&yaml).unwrap();
        assert_eq!(cfg.auth.registration_shared_secret.as_str(), Some("s3cret"));
        std::fs::remove_dir_all(dir).ok();
    }

    #[test]
    fn conflicting_secret_and_secret_file_is_an_error() {
        let yaml = "server:\n  server_name: example.org\nauth:\n  registration_shared_secret: inline\n  registration_shared_secret_file: /tmp/nope\n";
        let err = Config::from_yaml(yaml).unwrap_err();
        assert!(matches!(err, ConfigError::SecretConflict { .. }));
    }

    #[test]
    fn missing_secret_file_reports_its_path_and_field() {
        let yaml = "server:\n  server_name: example.org\nauth:\n  registration_shared_secret_file: /no/such/file\n";
        let err = Config::from_yaml(yaml).unwrap_err();
        match err {
            ConfigError::SecretFile { field, path, .. } => {
                assert_eq!(field, "auth.registration_shared_secret");
                assert_eq!(path, std::path::PathBuf::from("/no/such/file"));
            }
            other => panic!("expected SecretFile, got {other:?}"),
        }
    }

    #[test]
    fn multiple_validation_errors_are_all_reported() {
        let yaml = "server:\n  server_name: \"\"\nlisteners:\n  listeners: []\n";
        let err = Config::from_yaml(yaml).unwrap_err();
        match err {
            ConfigError::Validation(errors) => {
                assert!(
                    errors.0.len() >= 2,
                    "expected multiple errors, got {errors:?}"
                );
            }
            other => panic!("expected a validation error, got {other:?}"),
        }
    }

    #[test]
    fn default_config_is_not_directly_valid_without_a_server_name() {
        // Default::default() is useful for docs and tests but is not a
        // deployable config: server_name must be set explicitly.
        let mut errors = ValidationErrors::new();
        Config::default().server.validate("server", &mut errors);
        assert!(!errors.is_empty());
    }
}
