//! Fuzzes `hs_media::multipart::parse`, the `multipart/mixed` parser for federation media
//! responses (MSC3916). A remote homeserver — potentially malicious or compromised — controls
//! this body entirely, so it is fuzzed even though track 06's federation client, its only future
//! caller, does not exist yet (see `docs/rfcs/0007-federation-media.md`). Property under test:
//! never panics, never hangs (the parser's own bounded-iteration argument is in
//! `hs_media::multipart`'s module docs), whatever bytes arrive.
//!
//! The boundary string is fixed here (`"BOUNDARY"`) since libFuzzer's byte-string input maps most
//! usefully onto the body it frames, not onto arbitrary boundary syntax the server itself always
//! controls (it is generated by the server sending the response, echoed back in `Content-Type`,
//! never attacker-influenced independent of the body). `crate::multipart::boundary_from_content_type`
//! is exercised separately by this crate's own unit tests (`crates/hs-media/src/multipart.rs`).

#![no_main]

use hs_media::multipart::parse;
use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    let _ = parse("BOUNDARY", data);
});
