//! Exercises the committed test corpus (`tests/fixtures/images/`, generated by `cargo run -p
//! hs-media --example gen_fixtures`) against `hs_media::sniff` and `hs_media::thumbnail`: the
//! day-one work item from `docs/workstreams/09-media.md` ("a test corpus of images including
//! malformed and adversarial files") is not just files on disk, it is files this crate's own
//! decoding path is asserted to handle correctly -- valid ones decode and thumbnail, adversarial
//! ones fail cleanly (`Err`, never a panic).

use std::path::{Path, PathBuf};

use hs_media::sniff::{DecodeLimits, decode_with_limits};
use hs_media::thumbnail::{self, ThumbnailMethod};

fn fixture(name: &str) -> Vec<u8> {
    let path: PathBuf = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/images")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "missing fixture {} ({e}); run `cargo run -p hs-media --example gen_fixtures`",
            path.display()
        )
    })
}

#[test]
fn valid_png_decodes_and_thumbnails() {
    let bytes = fixture("valid.png");
    assert!(decode_with_limits(&bytes, DecodeLimits::default()).is_ok());
    assert!(
        thumbnail::generate(
            &bytes,
            32,
            32,
            ThumbnailMethod::Crop,
            DecodeLimits::default()
        )
        .is_ok()
    );
}

#[test]
fn valid_jpeg_decodes_and_thumbnails() {
    let bytes = fixture("valid.jpg");
    assert!(decode_with_limits(&bytes, DecodeLimits::default()).is_ok());
    assert!(
        thumbnail::generate(
            &bytes,
            32,
            32,
            ThumbnailMethod::Crop,
            DecodeLimits::default()
        )
        .is_ok()
    );
}

#[test]
fn valid_animated_gif_decodes_using_only_the_first_frame() {
    let bytes = fixture("valid_animated.gif");
    let (image, format) = decode_with_limits(&bytes, DecodeLimits::default()).unwrap();
    assert_eq!(format, image::ImageFormat::Gif);
    assert!(
        thumbnail::generate(
            &bytes,
            32,
            32,
            ThumbnailMethod::Crop,
            DecodeLimits::default()
        )
        .is_ok()
    );
    let _ = image;
}

#[test]
fn valid_webp_decodes_and_thumbnails() {
    let bytes = fixture("valid.webp");
    assert!(decode_with_limits(&bytes, DecodeLimits::default()).is_ok());
    assert!(
        thumbnail::generate(
            &bytes,
            32,
            32,
            ThumbnailMethod::Crop,
            DecodeLimits::default()
        )
        .is_ok()
    );
}

#[test]
fn decompression_bomb_is_rejected_without_a_huge_allocation() {
    let bytes = fixture("decompression_bomb.png");
    assert!(bytes.len() < 200, "the bomb fixture itself must stay tiny");
    let err = decode_with_limits(&bytes, DecodeLimits::default()).unwrap_err();
    assert!(matches!(err, hs_media::MediaError::DecodeFailed(_)));
}

#[test]
fn truncated_header_fails_cleanly() {
    let bytes = fixture("truncated_header.png");
    assert!(decode_with_limits(&bytes, DecodeLimits::default()).is_err());
}

#[test]
fn truncated_body_fails_cleanly() {
    let bytes = fixture("truncated_body.png");
    assert!(decode_with_limits(&bytes, DecodeLimits::default()).is_err());
}

#[test]
fn mismatched_extension_file_is_still_correctly_sniffed() {
    // Real JPEG bytes, saved with a `.png` name: `hs_media::sniff` looks at the bytes, not the
    // name/claimed type, so this must be detected as JPEG regardless.
    let bytes = fixture("mismatched_extension.png");
    let sniffed = hs_media::sniff::sniff_format(&bytes);
    assert_eq!(sniffed, Some(image::ImageFormat::Jpeg));
    assert!(!hs_media::sniff::format_matches_declared_type(
        "image/png",
        &bytes
    ));
}

#[test]
fn svg_is_never_treated_as_a_decodable_raster_image() {
    let bytes = fixture("adversarial.svg");
    assert!(decode_with_limits(&bytes, DecodeLimits::default()).is_err());
    assert_eq!(hs_media::sniff::sniff_format(&bytes), None);
    assert!(!hs_media::security::is_inline_safe("image/svg+xml"));
}

#[test]
fn html_masquerading_as_an_image_is_neither_decodable_nor_ever_inline() {
    let bytes = fixture("html_masquerading_as_image.png");
    assert!(decode_with_limits(&bytes, DecodeLimits::default()).is_err());
    assert_eq!(hs_media::sniff::sniff_format(&bytes), None);
    // Whatever Content-Type a client claimed for this upload, html is never served inline.
    assert!(!hs_media::security::is_inline_safe("text/html"));
}

#[test]
fn every_adversarial_fixture_fails_without_panicking() {
    for name in [
        "decompression_bomb.png",
        "truncated_header.png",
        "truncated_body.png",
        "adversarial.svg",
        "html_masquerading_as_image.png",
    ] {
        let bytes = fixture(name);
        // The assertion is just "this returns, does not panic" -- some of these do decode as
        // *something* (a truncated body might still parse a header), the point is no panic ever
        // reaches the caller regardless of which fixture is used.
        let _ = decode_with_limits(&bytes, DecodeLimits::default());
    }
}
