[package]
name = "hs-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true
description = "The `hs` binary: serve, single-node, import, appservice, cluster and compat subcommands"

[[bin]]
name = "hs"
path = "src/main.rs"

[lib]
name = "hs_cli"
path = "src/lib.rs"

[dependencies]
hs-config = { path = "../hs-config" }
hs-compat = { path = "../hs-compat" }
hs-auth = { path = "../hs-auth" }
hs-kv = { path = "../hs-kv" }
hs-telemetry = { path = "../hs-telemetry" }
hs-http = { path = "../hs-http" }
hs-room = { path = "../hs-room" }
hs-media = { path = "../hs-media" }
hs-appservice = { path = "../hs-appservice" }
hs-admin = { path = "../hs-admin" }
hs-model = { path = "../hs-model" }
object_store = { workspace = true }

clap = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
http = { workspace = true }
tower = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }
ed25519-dalek = { workspace = true, features = ["rand_core"] }
rand_core = { workspace = true }
rpassword = { workspace = true }
reqwest = { workspace = true }
ruma = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
