//! Renders a [`CoverageReport`] as Markdown, for `docs/status/` and the parity dashboard
//! (`tools/dashboard.py`, `docs/status/dashboard.md`).

use std::fmt::Write as _;

use crate::coverage::CoverageReport;

/// Renders `report` as a Markdown document: a summary table, then one section per API family
/// listing its missing routes (and extra routes, if any).
///
/// `missing_limit` caps how many missing routes are listed per family before the rest are
/// collapsed to a count (a family with zero registered routes, the day-one reality for every
/// surface here, would otherwise produce a multi-thousand-line report); pass `usize::MAX` for no
/// cap.
#[must_use]
pub fn render_markdown(report: &CoverageReport, missing_limit: usize) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# Matrix spec coverage report");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Generated by `hs-spec-coverage` (`crates/hs-spec-coverage`, track 14). Compares the Matrix \
         spec's OpenAPI trees (`refs/matrix-spec/data/api/`) against a `routes.json` router \
         manifest (`docs/rfcs/0005-routes-json-manifest.md`)."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "## Summary");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "| API | Spec routes | Registered | Missing | Extra | Coverage |"
    );
    let _ = writeln!(out, "|---|---:|---:|---:|---:|---:|");
    for api in &report.apis {
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} | {} | {:.1}% |",
            api.family,
            api.spec_total,
            api.registered,
            api.missing.len(),
            api.extra.len(),
            api.percent()
        );
    }
    let _ = writeln!(
        out,
        "| **Total** | **{}** | **{}** | **{}** | **{}** | **{:.1}%** |",
        report.total_spec_routes(),
        report.total_registered(),
        report.apis.iter().map(|a| a.missing.len()).sum::<usize>(),
        report.apis.iter().map(|a| a.extra.len()).sum::<usize>(),
        report.overall_percent()
    );
    let _ = writeln!(out);

    for api in &report.apis {
        let _ = writeln!(out, "## {}", api.family);
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "{} of {} spec routes registered ({:.1}%).",
            api.registered,
            api.spec_total,
            api.percent()
        );
        let _ = writeln!(out);

        if api.missing.is_empty() {
            let _ = writeln!(out, "No missing routes.");
        } else {
            let _ = writeln!(out, "### Missing ({})", api.missing.len());
            let _ = writeln!(out);
            for route in api.missing.iter().take(missing_limit) {
                let op = route.operation_id.as_deref().unwrap_or("-");
                let _ = writeln!(
                    out,
                    "- `{} {}` (`{}`, operationId `{}`)",
                    route.method, route.path, route.source_file, op
                );
            }
            if api.missing.len() > missing_limit {
                let _ = writeln!(out, "- ... and {} more", api.missing.len() - missing_limit);
            }
        }
        let _ = writeln!(out);

        if !api.extra.is_empty() {
            let _ = writeln!(
                out,
                "### Extra (registered, not in this spec checkout) ({})",
                api.extra.len()
            );
            let _ = writeln!(out);
            for (method, path) in &api.extra {
                let _ = writeln!(out, "- `{method} {path}`");
            }
            let _ = writeln!(out);
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::RouteManifest;
    use crate::spec::{ApiFamily, SpecRoute};

    #[test]
    fn renders_a_summary_table_and_missing_section() {
        let spec = vec![SpecRoute {
            method: "GET".to_string(),
            path: "/_matrix/client/v3/login".to_string(),
            family: ApiFamily::ClientServer,
            operation_id: Some("getLoginFlows".to_string()),
            source_file: "login.yaml".to_string(),
        }];
        let report = CoverageReport::compute(&spec, &RouteManifest::empty());
        let markdown = render_markdown(&report, 50);
        assert!(markdown.contains("# Matrix spec coverage report"));
        assert!(markdown.contains("| client-server | 1 | 0 | 1 | 0 | 0.0% |"));
        assert!(markdown.contains("getLoginFlows"));
    }

    #[test]
    fn caps_missing_list_and_reports_remainder_count() {
        let spec: Vec<SpecRoute> = (0..5)
            .map(|i| SpecRoute {
                method: "GET".to_string(),
                path: format!("/_matrix/client/v3/x{i}"),
                family: ApiFamily::ClientServer,
                operation_id: None,
                source_file: "x.yaml".to_string(),
            })
            .collect();
        let report = CoverageReport::compute(&spec, &RouteManifest::empty());
        let markdown = render_markdown(&report, 2);
        assert!(markdown.contains("... and 3 more"));
    }
}
