#!/usr/bin/env python3
"""Generate a parity inventory from a Synapse checkout.

Usage:
    git clone --depth 1 https://github.com/element-hq/synapse.git /tmp/synapse
    python3 tools/synapse_inventory.py /tmp/synapse > docs/synapse-inventory.md

The output is a Markdown checklist of every HTTP route pattern Synapse
registers (client, admin, media, federation, key, /_synapse/*), plus the
unstable_features it advertises, the room versions it knows, its config
option count, schema version, replication streams, module callbacks and test
counts. Re-run it on every Synapse release to diff the compatibility surface.
"""
import collections
import os
import re
import sys


def read(p):
    with open(p, encoding="utf8") as f:
        return f.read()


def routes(root):
    found = collections.defaultdict(list)
    for dp, _dn, fn in os.walk(os.path.join(root, "synapse")):
        for f in fn:
            if not f.endswith(".py"):
                continue
            p = os.path.join(dp, f)
            src = read(p)
            rel = os.path.relpath(p, root)
            for m in re.finditer(r'(client_patterns|admin_patterns)\(\s*(?:f?["\']([^"\']+)["\'])', src):
                found[m.group(1)].append((m.group(2), rel))
            for m in re.finditer(r'\bPATH\s*=\s*f?["\']([^"\']+)["\']', src):
                found["federation_PATH"].append((m.group(1), rel))
            for m in re.finditer(r're\.compile\(\s*f?["\'](\^?/_(?:matrix|synapse)[^"\']*)["\']', src):
                found["regex"].append((m.group(1), rel))
            for m in re.finditer(r'PATTERNS\s*=\s*\[\s*re\.compile\(\s*f?["\']([^"\']+)["\']', src):
                found["regex"].append((m.group(1), rel))
    return found


def main():
    root = sys.argv[1]
    version = re.search(r'^version\s*=\s*"([^"]+)"', read(os.path.join(root, "pyproject.toml")), re.M).group(1)
    schema = re.search(r"^SCHEMA_VERSION = (\d+)", read(os.path.join(root, "synapse/storage/schema/__init__.py")), re.M).group(1)
    print(f"# Synapse {version} compatibility inventory\n")
    print(f"Generated by tools/synapse_inventory.py. Schema version: {schema}.\n")

    found = routes(root)
    titles = {
        "client_patterns": "Client-Server routes (`/_matrix/client/{r0,v3,v1,unstable}` prefixes)",
        "admin_patterns": "Admin API routes (`/_synapse/admin/v{1,2,3}` prefixes)",
        "federation_PATH": "Federation transport routes (`/_matrix/federation/v{1,2}` prefixes)",
        "regex": "Other routes (media, keys, summaries, replication)",
    }
    for kind in ("client_patterns", "federation_PATH", "admin_patterns", "regex"):
        items = sorted(set(found[kind]))
        print(f"## {titles[kind]} ({len(items)})\n")
        for path, rel in items:
            print(f"- [ ] `{path}`  <sub>{rel}</sub>")
        print()

    vers = read(os.path.join(root, "rust/src/handlers/versions.rs"))
    feats = sorted(set(re.findall(r'"((?:org\.matrix|fi\.mau|uk\.half-shot|io\.element|de\.sorunome|com\.beeper)[a-zA-Z0-9_.\-]*)"', vers)))
    print(f"## `unstable_features` advertised by /versions ({len(feats)})\n")
    for f in feats:
        print(f"- [ ] `{f}`")
    print()
    specs = re.findall(r'"(v1\.\d+|r0\.[0-9.]+)"', vers)
    print("Spec versions advertised: " + ", ".join(sorted(set(specs))) + "\n")

    rv = read(os.path.join(root, "rust/src/room_versions.rs"))
    ids = sorted(set(re.findall(r'identifier: "([^"]+)"', rv)), key=lambda s: (not s.isdigit(), int(s) if s.isdigit() else 0, s))
    print(f"## Room versions known to Synapse ({len(ids)})\n")
    print(", ".join(f"`{i}`" for i in ids) + "\n")

    exp = read(os.path.join(root, "synapse/config/experimental.py"))
    mscs = sorted(set(re.findall(r'"(msc\d+[a-z_0-9]*)"', exp)))
    print(f"## experimental_features flags ({len(mscs)})\n")
    print(", ".join(f"`{m}`" for m in mscs) + "\n")

    doc = read(os.path.join(root, "docs/usage/configuration/config_documentation.md"))
    opts = re.findall(r"^### `([^`]+)`", doc, re.M)
    print(f"## Documented top-level config options ({len(opts)})\n")
    print(", ".join(f"`{o}`" for o in opts) + "\n")

    streams = set()
    for f in os.listdir(os.path.join(root, "synapse/replication/tcp/streams")):
        if f.endswith(".py"):
            streams |= set(re.findall(r'NAME = "([a-z_]+)"', read(os.path.join(root, "synapse/replication/tcp/streams", f))))
    print(f"## Replication streams ({len(streams)})\n")
    print(", ".join(f"`{s}`" for s in sorted(streams)) + "\n")

    cbs = set()
    cbdir = os.path.join(root, "synapse/module_api/callbacks")
    for f in os.listdir(cbdir):
        if f.endswith(".py"):
            cbs |= set(re.findall(r"def register_callbacks\([\s\S]*?\)", read(os.path.join(cbdir, f))))
    regs = set(re.findall(r"def (register_[a-z_]+callbacks)", read(os.path.join(root, "synapse/module_api/__init__.py"))))
    print(f"## Module API callback registries ({len(regs)})\n")
    print(", ".join(f"`{r}`" for r in sorted(regs)) + "\n")

    n = 0
    per = collections.Counter()
    for dp, _dn, fn in os.walk(os.path.join(root, "tests")):
        for f in fn:
            if f.endswith(".py"):
                c = len(re.findall(r"^\s+def test_", read(os.path.join(dp, f)), re.M))
                n += c
                per[os.path.relpath(dp, root).split(os.sep)[1] if os.sep in os.path.relpath(dp, root) else "tests"] += c
    print(f"## Synapse unit/integration tests ({n})\n")
    for k, v in per.most_common():
        print(f"- `tests/{k}`: {v}")
    print()


if __name__ == "__main__":
    main()
